version: '3'
services:
    relay:
        build: .
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: mysql:latest
        ports:
            - 3306:3006